database:
  fetching: file # [file, mysql, sqlite, mongo]
  details: # Only applies for dbs that require connection details
    host: localhost
    port: 3306
    database: test
    username: root
    password: ""

  cache: redis

